# Generated by Django 3.1.7 on 2021-03-11 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_auto_20210311_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmaterials',
            name='className',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class.class'),
        ),
        migrations.AlterField(
            model_name='classmaterials',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='class.classmaterialschapter'),
        ),
        migrations.AlterField(
            model_name='classmaterials',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='class.classmaterialsmodule'),
        ),
    ]
