# Generated by Django 3.1.7 on 2021-03-11 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_auto_20210311_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmaterialsmodule',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class.classmaterialschapter'),
        ),
    ]
