# Generated by Django 3.1.7 on 2021-03-12 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_classmaterialsmodule_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='classMaterial',
        ),
        migrations.AddField(
            model_name='files',
            name='ClassMaterialsModule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class.classmaterialsmodule'),
        ),
    ]
