# Generated by Django 3.1.7 on 2021-03-12 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0005_auto_20210312_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmaterialschapter',
            name='className',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class.class'),
        ),
    ]
