# Generated by Django 3.1.7 on 2021-03-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0006_classmaterialschapter_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmaterialschapter',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classmaterialsmodule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
