# Generated by Django 3.1.7 on 2021-03-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0007_auto_20210312_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmaterialschapter',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
