# Generated by Django 3.1.7 on 2021-03-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0008_classmaterialschapter_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
