# Generated by Django 3.1.7 on 2021-03-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0010_auto_20210312_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['date_added']},
        ),
        migrations.AddField(
            model_name='files',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
