# Generated by Django 3.1.7 on 2021-03-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0011_auto_20210312_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmaterialschapter',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='files',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
