# Generated by Django 3.1.7 on 2021-03-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0013_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-date_added']},
        ),
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.TextField(max_length=5000),
        ),
    ]
