# Generated by Django 3.1.7 on 2021-03-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0016_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='times',
            name='time',
        ),
        migrations.AddField(
            model_name='times',
            name='From',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='times',
            name='to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
