# Generated by Django 3.1.7 on 2021-03-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0017_auto_20210317_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='times',
            name='time',
            field=models.CharField(choices=[('8to930', '8:00 to 9:30'), ('930to11', '9:30 to 11:00'), ('11to1230', '11:00 to 12:30'), ('13to14:30', '13:00 to 14:30'), ('1430to16', '14:30 to 16:00')], default='00:00:00', max_length=32),
        ),
    ]
