# Generated by Django 3.1.7 on 2021-03-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0018_times_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='times',
            name='From',
        ),
        migrations.RemoveField(
            model_name='times',
            name='to',
        ),
    ]
