# Generated by Django 3.1.7 on 2021-03-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0019_auto_20210317_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='times',
            name='time',
            field=models.CharField(choices=[('8:00 to 9:30', '8:00 to 9:30'), ('9:30 to 11:00', '9:30 to 11:00'), ('11:00 to 12:30', '11:00 to 12:30'), ('13:00 to 14:30', '13:00 to 14:30'), ('14:30 to 16:00', '14:30 to 16:00')], default='00:00:00', max_length=32),
        ),
    ]
