# Generated by Django 3.1.7 on 2021-03-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0020_auto_20210317_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='times',
            options={'ordering': ['-time']},
        ),
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, default='noemail@email.com', max_length=254, null=True),
        ),
    ]
