# Generated by Django 3.1.7 on 2021-03-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0022_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
