# Generated by Django 3.1.7 on 2021-03-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0023_auto_20210319_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='dur_date',
            field=models.DateField(auto_now=True),
        ),
    ]
