# Generated by Django 3.1.7 on 2021-03-19 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0024_assignment_dur_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='dur_date',
            new_name='due_date',
        ),
    ]
