# Generated by Django 3.1.7 on 2021-03-19 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class', '0026_auto_20210319_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='files',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='submitted_by',
        ),
        migrations.CreateModel(
            name='SubmittedAssignments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='class.assignment')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
