# Generated by Django 3.1.7 on 2021-03-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0027_auto_20210319_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignments',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
