# Generated by Django 3.1.7 on 2021-03-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0029_auto_20210319_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedassignments',
            name='status',
            field=models.CharField(choices=[['awaiting submission', 'awaiting submission'], ('submitted', 'submitted'), ('graded', 'graded'), ('missed', 'missed')], default=['awaiting submission', 'awaiting submission'], max_length=100),
        ),
    ]
