# Generated by Django 3.1.7 on 2021-03-22 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0031_auto_20210319_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('time', models.IntegerField(help_text='Quiz duration in minutes')),
                ('score_to_pass', models.IntegerField(help_text='required score to pass the quiz in %')),
                ('created', models.DateTimeField(auto_now=True)),
                ('max_time_allowed', models.DateTimeField(help_text='The maximum date and time the users will be able to take the quiz')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.class')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.question')),
            ],
        ),
    ]
