# Generated by Django 3.1.7 on 2021-03-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0033_results'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='max_time_allowed',
            new_name='max_time_to_take',
        ),
    ]
