# Generated by Django 3.1.7 on 2021-03-25 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0036_results_submitted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
