# Generated by Django 3.1.7 on 2021-03-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0038_auto_20210325_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='number_of_total_grades',
            field=models.IntegerField(default=0),
        ),
    ]
