# Generated by Django 3.1.7 on 2021-03-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0039_grade_number_of_total_grades'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedassignments',
            name='submitted_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
