# Generated by Django 3.1.7 on 2021-03-30 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0042_auto_20210330_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enrollements_awaiting',
            new_name='EnrollementsAwaiting',
        ),
    ]
